const keyboardLayout = {
    ru: [
        ["Backquote", "usual", ["ё", "Ё"]],
        ["Digit1", "usual", ["1", "!"]],
        ["Digit2", "usual", ["2", "\""]],
        ["Digit3", "usual", ["3", "№"]],
        ["Digit4", "usual", ["4", ";"]],
        ["Digit5", "usual", ["5", "%"]],
        ["Digit6", "usual", ["6", ":"]],
        ["Digit7", "usual", ["7", "?"]],
        ["Digit8", "usual", ["8", "*"]],
        ["Digit9", "usual", ["9", "("]],
        ["Digit0", "usual", ["0", ")"]],
        ["Minus", "usual", ["-", "_"]],
        ["Equal", "usual", ["=", "+"]],
        ["Backspace", "special", "Backspace"],

        ["Tab", "special", "Tab"],
        ["KeyQ","usual", ["й", "Й"]],
        ["KeyW","usual", ["ц", "Ц"]],
        ["KeyE","usual", ["у", "У"]],
        ["KeyR","usual", ["к", "К"]],
        ["KeyT","usual", ["е", "Е"]],
        ["KeyY","usual", ["н", "Н"]],
        ["KeyU","usual", ["г", "Г"]],
        ["KeyI","usual", ["ш", "Ш"]],
        ["KeyO","usual", ["щ", "Щ"]],
        ["KeyP","usual", ["з", "З"]],
        ["BracketLeft", "usual", ["х", "Х"]],
        ["BracketRight", "usual", ["ъ", "Ъ"]],
        ["Backslash", "usual", ["\\", "/"]],

        ["Delete","special", "Del"],
        ["CapsLock","special", "Caps lock"],
        ["KeyA", "usual", ["ф", "Ф"]],
        ["KeyS", "usual", ["ы", "Ы"]],
        ["KeyD", "usual", ["в", "В"]],
        ["KeyF", "usual", ["а", "А"]],
        ["KeyG", "usual", ["п", "П"]],
        ["KeyH", "usual", ["р", "Р"]],
        ["KeyJ", "usual", ["о", "О"]],
        ["KeyK", "usual", ["л", "Л"]],
        ["KeyL", "usual", ["д", "Д"]],
        ["Semicolon", "usual", ["ж", "Ж"]],
        ["Quote", "usual", ["э", "Э"]],
        ["Enter", "special", "Enter"],

        ["ShiftLeft", "special", "Shift"],
        ["KeyZ", "usual", ["я", "Я"]],
        ["KeyX", "usual", ["ч", "Ч"]],
        ["KeyC", "usual", ["с", "С"]],
        ["KeyV", "usual", ["м", "М"]],
        ["KeyB", "usual", ["и", "И"]],
        ["KeyN", "usual", ["т", "Т"]],
        ["KeyM", "usual", ["ь", "Ь"]],
        ["Comma", "usual", ["б", "Б"]],
        ["Period", "usual", ["ю", "Ю"]],
        ["Slash", "usual", [".", ","]],
        ["ShiftRight", "special", "Shift"],
        ["ControlLeft", "special", "Ctrl"],
        ["MetaLeft", "special", "Win"],
        ["AltLeft", "special", "Alt"],
        ["Space", "special", " "],
        ["AltRight", "special", "Alt"],
        ["ControlRight", "special", "Ctrl"]
    ],
    en: [
        ["Backquote", "usual", ["`", "~"]],
        ["Digit1", "usual", ["1", "!"]],
        ["Digit2", "usual", ["2", "@"]],
        ["Digit3", "usual", ["3", "#"]],
        ["Digit4", "usual", ["4", "$"]],
        ["Digit5", "usual", ["5", "%"]],
        ["Digit6", "usual", ["6", "^"]],
        ["Digit7", "usual", ["7", "&"]],
        ["Digit8", "usual", ["8", "*"]],
        ["Digit9", "usual", ["9", "("]],
        ["Digit0", "usual", ["0", ")"]],
        ["Minus", "usual", ["-", "_"]],
        ["Equal", "usual", ["=", "+"]],
        ["Backspace", "special", "Backspace"],
    
        ["Tab", "special", "Tab"],
        ["KeyQ","usual", ["q", "Q"]],
        ["KeyW","usual", ["w", "W"]],
        ["KeyE","usual", ["e", "E"]],
        ["KeyR","usual", ["r", "R"]],
        ["KeyT","usual", ["t", "T"]],
        ["KeyY","usual", ["y", "Y"]],
        ["KeyU","usual", ["u", "U"]],
        ["KeyI","usual", ["i", "I"]],
        ["KeyO","usual", ["o", "O"]],
        ["KeyP","usual", ["p", "P"]],
        ["BracketLeft", "usual", ["[", "{"]],
        ["BracketRight", "usual", ["]", "}"]],
        ["Backslash", "usual", ["\\", "|"]],
        
        ["Delete","special", "Del"],
        ["CapsLock","special", "Caps lock"],
        ["KeyA", "usual", ["a", "A"]],
        ["KeyS", "usual", ["s", "S"]],
        ["KeyD", "usual", ["d", "D"]],
        ["KeyF", "usual", ["f", "F"]],
        ["KeyG", "usual", ["g", "G"]],
        ["KeyH", "usual", ["h", "H"]],
        ["KeyJ", "usual", ["j", "J"]],
        ["KeyK", "usual", ["k", "K"]],
        ["KeyL", "usual", ["l", "L"]],
        ["Semicolon", "usual", [";", ":"]],
        ["Quote", "usual", ["'", "\""]],
        ["Enter", "special", "Enter"],
        
        ["ShiftLeft", "special", "Shift"],
        ["KeyZ", "usual", ["z", "Z"]],
        ["KeyX", "usual", ["x", "X"]],
        ["KeyC", "usual", ["c", "C"]],
        ["KeyV", "usual", ["v", "V"]],
        ["KeyB", "usual", ["b", "B"]],
        ["KeyN", "usual", ["n", "N"]],
        ["KeyM", "usual", ["m", "M"]],
        ["Comma", "usual", [",", "<"]],
        ["Period", "usual", [".", ">"]],
        ["Slash", "usual", ["/", "?"]],
        ["ShiftRight", "special", "Shift"],
        ["ControlLeft", "special", "Ctrl"],
        ["MetaLeft", "special", "Win"],
        ["AltLeft", "special", "Alt"],
        ["Space", "special", " "],
        ["AltRight", "special", "Alt"],
        ["ControlRight", "special", "Ctrl"]
    ]
};

export default keyboardLayout;